Feat/s04 us01/upload
WildCodeSchool/2023-02-php-paris-p3-externatic pull request #13
Opened 2023-07-05 15:55 UTC by strmarlop

Dans le CandidateController, la méthode editUpload permet de uploader le CV.
Dans candidate/show.html.twig, le bouton 'update your resume' appelle à cette méthode.
Dans candidate/show.html.twig le bouton 'your resume' montre le CV du candidate, (preview avec modale).

2023-07-05 16:25 UTC, Erikaike requested changes

2023-07-05 16:25 UTC, Erikaike commented on src/Controller/CandidateController.php
> +        //Form edit/upload picture
commentaire inutile

2023-07-05 16:25 UTC, Erikaike commented on src/Entity/Candidate.php
> +    // #[Assert\File(maxSize: '1k')]
commentaire inutile

2023-07-05 16:25 UTC, Erikaike commented on src/Entity/Candidate.php
> +
une ligne vide en trop

2023-07-05 16:25 UTC, Erikaike commented on src/Entity/Candidate.php
> +        // return 'uploads/candidatePictures/' . $this->picture;
commentaire inutile

2023-07-05 16:25 UTC, Erikaike commented on src/Form/UploadResumeType.php
> +        ;
; à remettre sur la ligne de dessus

2023-07-05 21:36 UTC, mickaellambert requested changes

2023-07-05 21:36 UTC, mickaellambert commented on src/Controller/CandidateController.php
> +    public function editUpload(Request $request, Candidate $candidate, CandidateRepository $candidateRepository): Response
L'idée c'était justement de ne faire qu'une seule route edit et de l'appeler dans les deux cas !

2023-07-06 07:22 UTC, Erikaike approved these changes

2023-07-10 13:04 UTC, mickaellambert requested changes

2023-07-10 13:04 UTC, mickaellambert commented on src/Controller/CandidateController.php
> +// use App\Repository\OfferRepository;
bah ?

2023-07-10 13:04 UTC, mickaellambert commented on templates/candidate/show.html.twig
> +				{# {{ form_start(form) }} #}
bah ?

2023-07-10 13:44 UTC, mickaellambert approved these changes

2023-07-10 13:44 UTC, merged