:sparkles: Feat/S05US02/offer apply
WildCodeSchool/2023-02-php-paris-p3-externatic pull request #17
Opened 2023-07-11 18:46 UTC by Lionel-darosa

add apply button on offer and apply method

2023-07-12 07:57 UTC, strmarlop approved these changes

2023-07-12 08:48 UTC, mickaellambert requested changes

2023-07-12 08:48 UTC, mickaellambert commented on src/Controller/OfferController.php
> +            $offers = $offerRepository->findAll();
A faire comme avant, pas besoin de if else

2023-07-12 08:48 UTC, mickaellambert commented on src/Controller/OfferController.php
> +        $applied = false;
A faire via une requête SQL

2023-07-12 08:48 UTC, mickaellambert commented on src/Controller/OfferController.php
> +        $application = new Application();
tout le script dans une fonction, car doit être réutilisable

2023-07-12 08:48 UTC, mickaellambert commented on templates/Offer/show.html.twig
> +				{% if app.user.roles[0] == "ROLE_CANDIDATE" and not applied %}
vous avez surement une constante

2023-07-13 08:11 UTC, mickaellambert approved these changes

2023-07-13 08:11 UTC, merged