✨Feat/s04 us03/Crud_offer_Create
WildCodeSchool/2023-02-php-paris-p3-externatic pull request #22
Opened 2023-07-14 16:41 UTC by Erikaike

-OfferType form
-OfferController > new() method
-offer picture upload section with drag and drop
-CSS

2023-07-14 17:09 UTC, leahad requested changes
Très belle PR 🥇 :) je t'ai fait quelques suggestions ! a ta dispo pour en discuter si  besoin

2023-07-14 17:09 UTC, leahad commented on assets/styles/app.scss
> +
Pourrais-tu supprimer cet espace ? merci d'avance :)

2023-07-14 17:09 UTC, leahad commented on config/bundles.php
> +    Vich\UploaderBundle\VichUploaderBundle::class => ['all' => true],
Est-ce que tu pourrais le mettre ligne 18 pour que cela évite le bazard quand on va puller sur dev ? merci d'avance :)

2023-07-14 17:09 UTC, leahad commented on config/packages/security.yaml
> +            entry_point: form_login
Pourrais-tu supprimer les éléments qui concernent le fix du login car j'ai fait une US spécialement pour ça qui n' a pas encore été mérgée ?

2023-07-14 17:09 UTC, leahad commented on config/services.yaml
> +    upload_directory: '%kernel.project_dir%/public/uploads/offerPictures/'
Est-ce que tu pourrais utiliser la même méthode qu'Ester ici ? soit supprimer l'upload directory dans les services et plutôt mettre le lien dans le vich_uploader.yaml ? comme ça ce serait plus consistant avec le reste du code ? merci d'avance :)

2023-07-14 17:09 UTC, leahad commented on src/Entity/Offer.php
> +        mimeTypes: ['image/jpeg', 'image/png','image/jpg'],
Pourrais-tu ajouter un message d'erreur ici ?  tu peux cc ce que j'ai indiqué dans candidate pictureFile si besoin :) merci d'avance

2023-07-14 17:09 UTC, leahad commented on src/Form/OfferType.php
> +
pourrais-tu supprimer l'espace en trop ligne 59 ? merci d'avance :)

2023-07-14 17:09 UTC, leahad commented on src/Security/UserAuthenticator.php
>  }
Pourrais-tu supprimer cette partie cf mon comment plus haut ? merci d'avance :)

2023-07-14 18:02 UTC, leahad approved these changes
Parfait !

2023-07-17 07:16 UTC, mickaellambert approved these changes

2023-07-17 07:16 UTC, merged