✨ Feat/S05US05/crUd_offer_update
WildCodeSchool/2023-02-php-paris-p3-externatic pull request #23
Opened 2023-07-14 16:57 UTC by Erikaike

-OfferControler > edit() method
-CSS

2023-07-14 17:15 UTC, Lionel-darosa commented on src/Form/OfferType.php
> +
tu peux supprimer cette ligne

2023-07-14 19:51 UTC, Lionel-darosa approved these changes

2023-07-17 07:18 UTC, mickaellambert requested changes

2023-07-17 07:18 UTC, mickaellambert commented on config/packages/vich_uploader.yaml
> +        offers:
Tu respectes pas trop l'architecture la, tu rajoutes un dossier offerPIctures au même niveau que le dossier images

2023-07-17 07:18 UTC, mickaellambert commented on src/Controller/OfferController.php
>      #[IsGranted('ROLE_CANDIDATE')]
apparemment t'as un fail ici, on te dit "Attribute class Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted does not exist.
"

2023-07-17 08:10 UTC, mickaellambert approved these changes

2023-07-17 13:46 UTC, closed without merging