✨ Feat/S06US05bis/company-registration
WildCodeSchool/2023-02-php-paris-p3-externatic pull request #24
Opened 2023-07-15 14:11 UTC by leahad

- Created a company controller with a 'new' method
- Added a registration form dedicated to companies : CompanyType
- Added twig files : 'new' and '_form'

2023-07-15 15:09 UTC, Lionel-darosa approved these changes

2023-07-17 07:21 UTC, mickaellambert requested changes

2023-07-17 07:21 UTC, mickaellambert commented on config/packages/vich_uploader.yaml
> +            uri_prefix: /uploads/logos
pareil qu'erika, vous avez défini un dossier "images" dans "uploads", soit ce dernier est mal nommé, soit je m'attends à avoir des dossiers dans ce dossier la, mais pas au même niveau

2023-07-17 09:08 UTC, mickaellambert approved these changes

2023-07-17 14:27 UTC, mickaellambert approved these changes

2023-07-17 14:27 UTC, merged