✨ feat/S06US03/dashboard-candidate
WildCodeSchool/2023-02-php-paris-p3-externatic pull request #26
Opened 2023-07-16 16:44 UTC by leahad

Added a component dashboard in the candidate space

![dashboard visible here](https://github.com/WildCodeSchool/2023-02-php-paris-p3-externatic/assets/120429388/7d1c2f5b-0413-4d9d-90aa-3530162149b9)

2023-07-16 16:50 UTC, Lionel-darosa approved these changes

2023-07-17 07:36 UTC, mickaellambert requested changes

2023-07-17 07:36 UTC, mickaellambert commented on templates/candidate/_dashboard.html.twig
> +                {% set inReviewNbre = 0 %}
Nom de variable en anglais stp !

2023-07-17 07:36 UTC, mickaellambert commented on templates/candidate/_dashboard.html.twig
> +                {% set AcceptedNbre = 0 %}
Nom de variable en anglais et sans majuscule au début stp

2023-07-17 07:36 UTC, mickaellambert commented on templates/candidate/_dashboard.html.twig
> +                {% set rejecteddNbre = 0 %}
Nom de variable en anglais et avec un "d" en moins stp

2023-07-17 09:10 UTC, mickaellambert approved these changes

2023-07-17 14:28 UTC, mickaellambert approved these changes

2023-07-17 14:28 UTC, merged