🍻Fix/s07 us05/focus effect on navigation btns
WildCodeSchool/2023-02-php-paris-p3-externatic pull request #41
Opened 2023-07-22 09:03 UTC by Erikaike

-add the active class on buttons on the condition to be on the route related to the said button
-set the background color on yellow in app.js

2023-07-22 09:19 UTC, leahad requested changes
BRAVO !!!  quelques modifs et on est bon :)

2023-07-22 09:19 UTC, leahad commented on migrations/Version20230722080042.php
> +<?php
Pourrais-tu supprimer le fichier de migration ? merci d'avance !

2023-07-22 09:19 UTC, leahad commented on src/Security/UserAuthenticator.php
pourrais-tu supprimer les modifications réalisées sur ce fichier ?  merci d'avance

2023-07-22 09:19 UTC, leahad commented on templates/Offer/edit.html.twig
> +<<<<<<< HEAD:templates/offer_type/edit.html.twig
Pourrais-tu supprimer les éléments issues du merge tels que 
"<<<<<<< HEAD:templates/offer_type/edit.html.twig"
"======="
">>>>>>> dev:templates/Offer/edit.html.twig"
Merci !

2023-07-22 09:19 UTC, leahad commented on templates/company/_dashboard.html.twig
> -    <h3 class="p-4">Welcome {{ app.user.company.name }} :)</h3>
Pourquoi avoir remove le smiley ?  on pourrait en discuter tous ensemble lundi si tu ne trouves pas cela pertinent ?

2023-07-22 09:19 UTC, leahad commented on templates/style/component/_navigationBtnDesktopCandidate.html.twig
> +{% include 'style/component/_btnBgStyle.js' %}
Pourrais-tu supprimer le script ici ? merci d'avance :)

2023-07-22 09:19 UTC, leahad commented on templates/style/component/_navigationBtnMobileCandidate.html.twig
> +{% include 'templates/style/component/_btnBgStyle.js' %}
Pourrais-tu supprimer le script ici ? merci d'avance :)

2023-07-22 09:49 UTC, leahad approved these changes
ALL GOOD !

2023-07-24 07:19 UTC, mickaellambert approved these changes

2023-07-24 07:19 UTC, merged