🍻 Fix/s08 us01/candidate-space-final-fixes
WildCodeSchool/2023-02-php-paris-p3-externatic pull request #48
Opened 2023-07-24 14:47 UTC by Erikaike

-edit bouton (Candidate Profile) put in <a> tag -réecriture des titres des pages
-different redirection and flash messages after adding/removing a favorite 
-removed "show profile" in menu
-pages title checked and changed

2023-07-24 14:55 UTC, strmarlop requested changes

2023-07-24 14:55 UTC, strmarlop commented on src/Controller/CandidateController.php
> +    public function show(Candidate $candidate, Request $request): Response
Il faudrait enlever le Request là. Merciiii :)

2023-07-24 14:55 UTC, strmarlop commented on templates/company/indexOffer.html.twig
> +	{{ company.name }}'s Offers
Est-ce que tu pourrais mettre Offers en minúscule? Merciii :)

2023-07-24 15:05 UTC, strmarlop approved these changes

2023-07-25 07:18 UTC, mickaellambert approved these changes

2023-07-25 07:18 UTC, merged