🍻Fix/s08 us04/company fixes
WildCodeSchool/2023-02-php-paris-p3-externatic pull request #51
Opened 2023-07-24 16:21 UTC by Erikaike

2023-07-24 16:35 UTC, leahad requested changes
à part 2 mofifs, RAS 👍

2023-07-24 16:35 UTC, leahad commented on src/Form/CompanyType.php
Les contraintes sont déjà dans l'entité, donc si tu les rajoutes ici, cela va faire 2 messages d'erreurs. Est- ce que tu pourrais les supprimer  ligne 26, 39 , 48 et 72 ? merci d'avance !

2023-07-24 16:35 UTC, leahad commented on templates/Offer/new.html.twig
> +{% block title %}Create a new Offer {% endblock %}
est-ce que tu pourrais supprimer l'espace après "Offer" et enlever la majuscule à "offer" ? merci d'avance :)

2023-07-24 17:28 UTC, leahad requested changes
une micro modif and all good

2023-07-24 17:28 UTC, leahad commented on templates/Offer/new.html.twig
> +{% block title %}Create a new offer {% endblock %}
pourrais-tu suuprimer l'espace après offer ? merci !

2023-07-24 17:33 UTC, leahad approved these changes
YES !

2023-07-25 07:20 UTC, leahad approved these changes

2023-07-25 07:23 UTC, mickaellambert approved these changes

2023-07-25 07:23 UTC, merged