✨ Feat/s02 us03/offer show
WildCodeSchool/2023-02-php-paris-p3-externatic pull request #6
Opened 2023-06-26 18:18 UTC by Erikaike

-S02US03 - (BIG US )En tant que candidat, je veux pouvoir acceder à une offre et postuler
-Fixed constants (from Fixtures files to entities files)
-OfferController with routes, views and methods index(), show() and apply()

2023-06-27 07:10 UTC, strmarlop approved these changes
Good job!!!! :D

2023-06-27 14:16 UTC, mickaellambert requested changes

2023-07-03 10:27 UTC, leahad reviewed
avec les commentaires vu ensemble :)

2023-07-03 10:27 UTC, leahad commented on assets/styles/app.scss
> +
pourrais-tu supprimer l'espace en dessous de page Offer_index ? merci d'avance :)

2023-07-03 10:27 UTC, leahad commented on assets/styles/app.scss
> +
pourrais-tu supprimer l'espace après paginator et enlever les parenthèses ? merci d'avance :)

2023-07-03 10:27 UTC, leahad commented on assets/styles/app.scss
> +
pourrais-tu supprimer l'espace en dessous de page Offer_show ? merci d'avance :)

2023-07-03 10:27 UTC, leahad commented on assets/styles/app.scss
> +@import "~bootstrap/scss/bootstrap";
Pourrais-tu mettre le lien bootstrap à la fin du fichier ? merci d'avance :)

2023-07-03 10:27 UTC, leahad commented on assets/styles/app.scss
> +.btn {
serait-il possible de changer le nom de ta classe pour que cela n'impacte pas tous les boutons ? merci d'avance :)

2023-07-03 14:12 UTC, mickaellambert approved these changes

2023-07-03 14:12 UTC, merged