✨ Feat/S02US01/Crud candidate
WildCodeSchool/2023-02-php-paris-p3-externatic pull request #7
Opened 2023-06-27 13:10 UTC by strmarlop

CRUD candidate.
Développé le show profile du candidate et le CSS mobile et desktop.

2023-06-27 14:03 UTC, leahad requested changes
à part les quelques modifs cela est parfait :) bravo !!

2023-06-27 15:38 UTC, strmarlop commented
Changements faits!

2023-06-28 07:26 UTC, leahad approved these changes

2023-07-03 07:16 UTC, mickaellambert requested changes

2023-07-03 09:53 UTC, leahad approved these changes
Nickel <3

2023-07-03 10:00 UTC, strmarlop commented on src/Form/CandidateType.php
> +    public function buildForm(FormBuilderInterface $builder, array $options): void
J'ai essayé de supprimer le fichier, mais après sur GitHub marquait des erreurs sur le code quality genre CandidateType n'existe pas.. :S

2023-07-03 10:02 UTC, leahad approved these changes

2023-07-04 06:44 UTC, mickaellambert approved these changes

2023-07-04 06:44 UTC, merged