:sparkles: Feat/s02 us02/offers filter
WildCodeSchool/2023-02-php-paris-p3-externatic pull request #8
Opened 2023-07-02 13:14 UTC by Lionel-darosa

En tant que candidat, je veux pouvoir filtrer les offres d'emploi

2023-07-02 18:12 UTC, Erikaike requested changes

2023-07-03 14:05 UTC, Erikaike approved these changes

2023-07-04 06:45 UTC, mickaellambert approved these changes

2023-07-04 06:45 UTC, mickaellambert commented on assets/styles/app.scss
> +
Erika a raison, restez toujours cohérents dans vos fichiers

2023-07-04 06:45 UTC, mickaellambert commented on src/Entity/Company.php
> +        'Connected Object' => 'Connected Object',
Ah bah oui elle a encore raison

2023-07-04 06:45 UTC, mickaellambert commented on src/Entity/Offer.php
> +        'fixed-term / temporary' => 'fixed-term / temporary',
+1

2023-07-04 06:45 UTC, mickaellambert commented on src/Entity/Offer.php
> +        '10+' => '10+',
+1

2023-07-04 06:45 UTC, mickaellambert commented on src/Entity/Offer.php
> +        'Occasional remote' => 'Occasional remote',
+1

2023-07-04 08:46 UTC, merged